---
creation_rules:
  - path_regex: ^\.enc\.env$
    encrypted_regex: (^SECRET_[a-zA-Z0-9_]*)
    # Local, VyOS
    age: >-
      age150tjn37jsl7j9un969ycdwn33gf7wxzzyxsv2qsn43akfxhvp5vq0herz2,
      age1rmmltzuwlpam395yp9d8l730d36padjaav5n09js2ddg7gzjlakqyf8uxl
