#!/bin/vbash

# LAN
set firewall zone lan description 'LAN backbone'
set firewall zone lan default-action 'drop'
set firewall zone lan from local firewall name 'local-lan'
set firewall zone lan from services firewall name 'services-lan'
set firewall zone lan from management firewall name 'management-lan'
set firewall zone lan from servers firewall name 'servers-lan'
set firewall zone lan from trusted firewall name 'trusted-lan'
set firewall zone lan from guest firewall name 'guest-lan'
set firewall zone lan from iot firewall name 'iot-lan'
set firewall zone lan from wan firewall name 'wan-lan'
set firewall zone lan interface 'eth1'

# LOCAL
set firewall zone local description 'Local router zone'
set firewall zone local default-action 'drop'
set firewall zone local from lan firewall name 'lan-local'
set firewall zone local from services firewall name 'services-local'
set firewall zone local from management firewall name 'management-local'
set firewall zone local from servers firewall name 'servers-local'
set firewall zone local from trusted firewall name 'trusted-local'
set firewall zone local from guest firewall name 'guest-local'
set firewall zone local from iot firewall name 'iot-local'
set firewall zone local from wan firewall name 'wan-local'
set firewall zone local local-zone

# SERVICES
set firewall zone services description 'VyOS services zone'
set firewall zone services default-action 'drop'
set firewall zone services from lan firewall name 'lan-services'
set firewall zone services from local firewall name 'local-services'
set firewall zone services from management firewall name 'management-services'
set firewall zone services from servers firewall name 'servers-services'
set firewall zone services from trusted firewall name 'trusted-services'
set firewall zone services from guest firewall name 'guest-services'
set firewall zone services from iot firewall name 'iot-services'
set firewall zone services from wan firewall name 'wan-services'
set firewall zone services interface 'pod-services'

# SERVERS
set firewall zone servers description 'Servers zone'
set firewall zone servers default-action 'drop'
set firewall zone servers from lan firewall name 'lan-servers'
set firewall zone servers from local firewall name 'local-servers'
set firewall zone servers from services firewall name 'services-servers'
set firewall zone servers from management firewall name 'management-servers'
set firewall zone servers from trusted firewall name 'trusted-servers'
set firewall zone servers from guest firewall name 'guest-servers'
set firewall zone servers from iot firewall name 'iot-servers'
set firewall zone servers from wan firewall name 'wan-servers'
set firewall zone servers interface 'eth1.10'

# TRUSTED
set firewall zone trusted description 'Trusted zone'
set firewall zone trusted default-action 'drop'
set firewall zone trusted from lan firewall name 'lan-trusted'
set firewall zone trusted from local firewall name 'local-trusted'
set firewall zone trusted from services firewall name 'services-trusted'
set firewall zone trusted from management firewall name 'management-trusted'
set firewall zone trusted from servers firewall name 'servers-trusted'
set firewall zone trusted from guest firewall name 'guest-trusted'
set firewall zone trusted from iot firewall name 'iot-trusted'
set firewall zone trusted from wan firewall name 'wan-trusted'
set firewall zone trusted interface 'eth1.20'
set firewall zone trusted interface 'wg01'

# IOT
set firewall zone iot description 'IoT zone'
set firewall zone iot default-action 'drop'
set firewall zone iot from lan firewall name 'lan-iot'
set firewall zone iot from local firewall name 'local-iot'
set firewall zone iot from services firewall name 'services-iot'
set firewall zone iot from management firewall name 'management-iot'
set firewall zone iot from servers firewall name 'servers-iot'
set firewall zone iot from trusted firewall name 'trusted-iot'
set firewall zone iot from guest firewall name 'guest-iot'
set firewall zone iot from wan firewall name 'wan-iot'
set firewall zone iot interface 'eth1.40'
set firewall zone iot interface 'eth2' # to UDMP

# MANAGEMENT
set firewall zone management description 'Management zone'
set firewall zone management default-action 'drop'
set firewall zone management from lan firewall name 'lan-management'
set firewall zone management from local firewall name 'local-management'
set firewall zone management from services firewall name 'services-management'
set firewall zone management from servers firewall name 'servers-management'
set firewall zone management from trusted firewall name 'trusted-management'
set firewall zone management from guest firewall name 'guest-management'
set firewall zone management from wan firewall name 'wan-management'
set firewall zone management interface 'eth1.50'

# GUEST
set firewall zone guest description 'Guest zone'
set firewall zone guest default-action 'drop'
set firewall zone guest from lan firewall name 'lan-guest'
set firewall zone guest from local firewall name 'local-guest'
set firewall zone guest from services firewall name 'services-guest'
set firewall zone guest from management firewall name 'management-guest'
set firewall zone guest from servers firewall name 'servers-guest'
set firewall zone guest from trusted firewall name 'trusted-guest'
set firewall zone guest from iot firewall name 'iot-guest'
set firewall zone guest from wan firewall name 'wan-guest'
set firewall zone guest interface 'eth1.30'

# WAN
set firewall zone wan description 'WAN'
set firewall zone wan default-action 'drop'
set firewall zone wan from lan firewall name 'lan-wan'
set firewall zone wan from local firewall name 'local-wan'
set firewall zone wan from services firewall name 'services-wan'
set firewall zone wan from management firewall name 'management-wan'
set firewall zone wan from servers firewall name 'servers-wan'
set firewall zone wan from trusted firewall name 'trusted-wan'
set firewall zone wan from guest firewall name 'guest-wan'
set firewall zone wan from iot firewall name 'iot-wan'
set firewall zone wan interface 'eth0'
